name: SkyFactions
version: 1.1
main: me.marshmallow353.skyfactions.SkyFactions
api-version: 1.12
description: My first plugin!
depend: [Factions]
commands:
  sf:
    description: All SkyFactions Commands!
    usage: /sf create

